%% Define ABM Sites %%

%  This function simply creates a struct which contains the values for each
%  ABM. You can import the values by writing site.namesite (e.g.  
%  color.light_grey)

site = struct(...
        'cortical_bone_induced', -3, ...
        'outer'         , -2, ...  
        'cortical_bone' , -1, ... 
        'bone_marrow'   ,  0, ... 
        'tumor_edge'    ,  1, ...
        'tumor'         ,  2, ... 
        'vessel'        ,  3, ... 
        'vessel_cabo'   ,  4, ... 
        'osteoblast'    ,  5, ...
        'osteoclast'    ,  6, ...
        'mitotic_cell'  ,  7, ...
        'apoptotic_cell', 8);